sudo: false

language: node_js
node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules

install:
  - yarn --frozen-lockfile --silent --non-interactive
  - yarn --frozen-lockfile --silent --non-interactive --cwd example

script:
  - yarn type-check
  - yarn --cwd example type-check
  - yarn test --coverage

after_success:
  - yarn global add codecov coveralls
  - codecov && coveralls < ./coverage/lcov.info

notifications:
  email: false
